### ISSUE TITLE
Question: Icons and https

### ISSUE THREAD

**Issue by MvErven** [LotarProject/dokuwiki-plugin-icons#16]
Question. Will icons plugin still work when browser(s) are only accepting https?
Rawgrit will start to redirect http to https.

![iconsplugin](https://user-images.githubusercontent.com/17900348/36141524-4db15c0a-10a5-11e8-917f-852fbd938f72.png)

![freeiconsfonts](https://user-images.githubusercontent.com/17900348/36141527-52cb6aaa-10a5-11e8-8fc7-aa2ebc57d2f7.png)

**Comment by LotarProject** [comment]
Hi @MvErven,
Actually the default configuration have "//" prefix for most URL to use "https" only if the page are in "https".

Download the next release of plugin (v2018-02-14) to prevent this issue.

In the next release most icons packs will be included in the Icon Plugin package. This solution reduce the page loading and is useful on intranet DokuWiki installations.

At your disposal,
Joseph

**Comment by MvErven** [comment]
Thank you Joseph, and you're welcome.
Will have a try tomorrow.
