### ISSUE TITLE
local path in popup window

### ISSUE THREAD

**Issue by nurzu** [LotarProject/dokuwiki-plugin-icons#17]
### Description

Icons for Alignment and Image size doesn't show up in new popup window 

### Steps to reproduce

1. Clicking the plugin-icon in the toolbar
2. Popup-window opens 

**Expected behavior:** Icons should appear 
**Actual behavior:** Icons missing (screenshot)

### Versions

[Bootstrap3 Template] v2018-02-16
[DokuWiki] Release 2017-02-19e “Frusterick Manners”
[Plugins] Bootstrap3 Template, Bootswrapper, Icons
[Browser] All modern browsers

### Screenshots or Logs

![missing icons](https://user-images.githubusercontent.com/36882769/36785574-962e74e2-1c83-11e8-91fb-4bf95ed4abd5.png)

### Sample page or snippet

Checking the source of the missing icons, it leads to localhost/…

**Comment by PauloMad** [comment]
Having the same issue!

**Comment by LotarProject** [comment]
Hi, i have fixed this issue.

You can update the plugin from extension manager and retry ?

Thanks
Joseph

**Comment by nurzu** [comment]
Now it's just fine. Thanks again!
