### ISSUE TITLE
RPG-AWESOME icons not showing

### ISSUE THREAD

**Issue by PauloMad** [LotarProject/dokuwiki-plugin-icons#18]
**Description**
Icons for Rpg-Awesome pack not showing when inserted anywhere in the wiki.

**Steps to reproduce**
Clicking the plugin-icon in the toolbar
Popup-window opens
Chose rpg icon
Inserts the tag ok
Preview and after publish not showing icon

Note: all other icon packs post and show fine.

**Versions**
[Bootstrap3 Template] v2018-02-16
[DokuWiki] Release 2017-02-19e “Frusterick Manners”
[Plugins] Bootstrap3 Template, Bootswrapper, Icons
[Browsers tested] Latest Chrome + Firefox

**Comment by ajreaper** [comment]
I just figured this out myself. Fortunately, it was an easy fix.

Go to: /YourWikiName/lib/plugins/icons/exe/popup.php
Line 240
Change:
`<a data-toggle="tab" href="#tab-rpg-awesome" data-pack="fl">RPG-Awesome</a>`
To
`<a data-toggle="tab" href="#tab-rpg-awesome" data-pack="ra">RPG-Awesome</a>`

**Comment by LotarProject** [comment]
@ajreaper and @PauloMad i have fixed this issue in last release of plugins.

Thanks!
Joseph
