### ISSUE TITLE
Unable to use plugin in links

### ISSUE THREAD

**Issue by lazyzero** [LotarProject/dokuwiki-plugin-icons#3]
Hi,

I tried to use the icons plugin for decorating links 

```
[[https://twitter.com|{{fa>fa fa-twitter?24}}]]
```
but that doesn't work. Can you please advice what the problem could be?

Best Christian

**Comment by lazyzero** [comment]
Okay, found out that this is a limitation of the core link syntax.

**Comment by LotarProject** [comment]
Yes. I had the same idea of your pull request ;)
