### ISSUE TITLE
Icons disappear and links break when other links on page

### ISSUE THREAD

**Issue by atomparticle** [LotarProject/dokuwiki-plugin-icons#7]
When other link doesn't have a description, that link becomes part of the icon's link. When it does have a description, the icon disappears completely.

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue.
Can you send a little snippet for reproduce in my dev environment ?

At your disposal!
Joseph

**Comment by atomparticle** [comment]
[[/about|About page]]

[[go/twitter|{{icon>twitter-square?42|Follow us}}]]
[[go/facebook|{{icon>facebook-square?42|Like us}}]]

This code outputs:
```<i class="/about /about-" style="font-size:16px" title="About page]] [[go/twitter}}"></i>```, so both the About link and Twitter icons are gone. The Facebook icon displays normally.

I got around the problem by putting them on a separate page and including via include plugin.

Thanks!
