### ISSUE TITLE
After updating it seems that size doesn't matter...

### ISSUE THREAD

**Issue by atomparticle** [LotarProject/dokuwiki-plugin-icons#8]
After updating to the latest version, all my icons are small size. Even changing the default size in config doesn't make a difference. At least not for FontAwesome.

**Comment by LotarProject** [comment]
Hi! I have tested in my dev environment and in my main website and don't have this behavior.

Can you test in your DokuWiki installation this snippet and change the ``defaultSize`` config (eg. 16, 32, 64)?

````
^ Default size | {{oxygen>places/user-home}} |
^ 16px  | {{oxygen>places/user-home?16}} |
^ 22px  | {{oxygen>places/user-home?22}} |
^ 32x   | {{oxygen>places/user-home?32}} |
^ 64px  | {{oxygen>places/user-home?64}} |
^ 128px | {{oxygen>places/user-home?128}} |
````

At your disposal,
Joseph

**Comment by atomparticle** [comment]
After checking, I have no problem when specifying the icon pack, only when using the {{icon>...}} syntax. My default pack is set to Font Awesome, this is what I get from using {{icon>home?128}}
```<i class="fa fa-home" style="" title=""></i>```
and this is what I get when using {{fa>home?128}}:
```<i class="fa fa-home" style="font-size:128px" title=""></i>```

Hope that helps!
